name: Update README Stats

on:
  push:
    paths:
      - '.github/scripts/challengeData.json'
  schedule:
    - cron: "0 15 * * 5"
  workflow_dispatch:

jobs:
  update_readme:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      #- name: Setup Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: '18'

      - name: Write Update to README.md
        run: |
          node .github/scripts/getStatsFromEntwicklerHeld.js

      - name: Commit changes
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add -A
            git commit -m "(docs): Update README.md" || exit 0
            git push
