name: Update Main README Stats

on:
  push:
    paths:
      - '.github/scripts/challengeData.json'
  schedule:
    - cron: "* * * * 4"
  workflow_dispatch

jobs:
  update_readme:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .
            .github

#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '14' # You can change this to your preferred Node.js version

#      - name: Run updateReadme.js
#        run: node updateReadme.js > README.md

#      - name: Commit changes
#       run: |
#          git config --global user.name "GitHub Actions"
#          git config --global user.email "actions@github.com"
#          git add README.md
#          git commit -m "Update README.md with new content from updateReadme.js"
#          git push


